using SharpHunter.Utils;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using System.ComponentModel;
using System.Security.Principal;

namespace SharpHunter.Commands
{
    public class ProcessCommand : ICommand
    {
        public struct ProcessInfo
        {
            public string ProcessName;
            public int ProcessId;
            public string Architecture;
            public string FilePath;
            public string UserName;
        }

        public struct MarkedProcessInfo
        {
            public string ProcessName;
            public int PID;
            public string Arch;
            public string Note;
        }

        public void Execute(List<string> args)
        {
            PrintProcessInfo();
        }
        public void PrintProcessInfo(string outputPath=null)
        {
            Logger.TaskHeader("Marked Process", 1);
            var processInfos = CollectProcessInfo();
            var markedProcessInfos = GetMarkedProcessInfo(processInfos);
            Logger.PrintTableFromStructs(markedProcessInfos);
            if (outputPath != null)
            {
                Logger.WriteStructsToCsv(processInfos, outputPath, "ProcessInfo.csv");
            }
        }

        public List<ProcessInfo> CollectProcessInfo()
        {
            var processInfoList = new List<ProcessInfo>();

            uint[] processIds = new uint[1024];
            uint bytesReturned;

            if (!Win32.EnumProcesses(processIds, (uint)processIds.Length * sizeof(uint), out bytesReturned))
            {
                throw new Win32Exception(Marshal.GetLastWin32Error());
            }

            int processCount = (int)(bytesReturned / sizeof(uint));

            for (int i = 0; i < processCount; i++)
            {
                IntPtr hProcess = Win32.OpenProcess(Win32.PROCESS_QUERY_INFORMATION | Win32.PROCESS_VM_READ, false, processIds[i]);
                if (hProcess == IntPtr.Zero)
                {
                    continue;
                }

                try
                {
                    StringBuilder fileName = new StringBuilder(1024);
                    if (Win32.GetModuleFileNameEx(hProcess, IntPtr.Zero, fileName, fileName.Capacity) == 0)
                    {
                        continue;
                    }

                    string userName = GetProcessUser(hProcess) ?? "N/A";
                    bool is64Bit = Is64BitProcess(hProcess);
                    string architecture = is64Bit ? "x64" : "x86";

                    processInfoList.Add(new ProcessInfo
                    {
                        ProcessName = System.IO.Path.GetFileName(fileName.ToString()),
                        ProcessId = (int)processIds[i],
                        Architecture = architecture,
                        FilePath = fileName.ToString(),
                        UserName = userName
                    });
                }
                finally
                {
                    Win32.CloseHandle(hProcess);
                }
            }

            return processInfoList.OrderBy(p => p.ProcessName, StringComparer.OrdinalIgnoreCase).ToList();
        }

        private string GetProcessUser(IntPtr hProcess)
        {
            IntPtr tokenHandle = IntPtr.Zero;
            try
            {
                if (!Win32.OpenProcessToken(hProcess, Win32.TOKEN_QUERY, out tokenHandle))
                {
                    return null;
                }

                uint tokenInfoLength = 0;
                Win32.GetTokenInformation(tokenHandle, Win32.TOKEN_INFORMATION_CLASS.TokenUser, IntPtr.Zero, 0, out tokenInfoLength);
                IntPtr tokenInfo = Marshal.AllocHGlobal((int)tokenInfoLength);
                try
                {
                    if (Win32.GetTokenInformation(tokenHandle, Win32.TOKEN_INFORMATION_CLASS.TokenUser, tokenInfo, tokenInfoLength, out tokenInfoLength))
                    {
                        var tokenUser = (Win32.TOKEN_USER)Marshal.PtrToStructure(tokenInfo, typeof(Win32.TOKEN_USER));

                        uint nameLength = 256;
                        uint domainLength = 256;
                        StringBuilder name = new StringBuilder((int)nameLength);
                        StringBuilder domain = new StringBuilder((int)domainLength);

                        if (Win32.LookupAccountSid(null, tokenUser.User.Sid, name, ref nameLength, domain, ref domainLength, out int _))
                        {
                            return domain.Length > 0 ? $"{domain}\\{name}" : name.ToString();
                        }
                    }
                }
                finally
                {
                    Marshal.FreeHGlobal(tokenInfo);
                }
            }
            catch
            {
                // Ignored
            }
            finally
            {
                if (tokenHandle != IntPtr.Zero)
                {
                    Win32.CloseHandle(tokenHandle);
                }
            }

            return null;
        }

        public List<MarkedProcessInfo> GetMarkedProcessInfo(List<ProcessInfo> processInfos)
        {
            var markedProcessInfos = new List<MarkedProcessInfo>();
            
            foreach (var process in processInfos)
            {
                if (KnownProcesses.TryGetValue(process.ProcessName.ToLower(), out string note))
                {
                    markedProcessInfos.Add(new MarkedProcessInfo
                    {
                        ProcessName = process.ProcessName,
                        PID = process.ProcessId,
                        Arch = process.Architecture,
                        Note = note
                    });
                }
            }
            
            return markedProcessInfos.OrderBy(p => p.ProcessName, StringComparer.OrdinalIgnoreCase).ToList();
        }

        private bool Is64BitOperatingSystem()
        {
            return IntPtr.Size == 8 || !string.IsNullOrEmpty(Environment.GetEnvironmentVariable("PROCESSOR_ARCHITEW6432"));
        }

        private bool Is64BitProcess(IntPtr hProcess)
        {
            if (!Is64BitOperatingSystem())
                return false;

            try
            {
                if (Win32.IsWow64Process(hProcess, out bool isWow64))
                {
                    return !isWow64;
                }
            }
            catch
            {
                // Ignored
            }

            return false;
        }

        private static readonly Dictionary<string, string> KnownProcesses = new Dictionary<string, string>
        {
            { "360bpsvc.exe", "360安全浏览器的防护服务进程" },
            { "360entclient.exe", "天擎edr agent" },
            { "360EntClient.exe", "天擎EDR Agent" },
            { "360rp.exe", "疑似杀软进程" },
            { "360safe.exe", "360安全卫士-主程序" },
            { "360safebox.exe", "疑似杀软进程" },
            { "360sd.exe", "360杀毒" },
            { "360se.exe", "360 安全浏览器" },
            { "360Tray.exe", "360安全卫士-实时保护" },
            { "360tray.exe", "360安全卫士-实时保护" },
            { "_avp32.exe", "疑似杀软进程" },
            { "_avpcc.exe", "疑似杀软进程" },
            { "_avpm.exe", "疑似杀软进程" },
            { "A2CMD.exe", "Emsisoft Anti-Malware" },
            { "a2cmd.exe", "emsisoft anti-malware" },
            { "A2FREE.exe", "a-squared Free" },
            { "a2free.exe", "a-squared free" },
            { "a2guard.exe", "a-squared杀毒" },
            { "A2SERVICE.exe", "a-squared free" },
            { "a2service.exe", "a-squared free" },
            { "aAvgApi.exe", "AVG" },
            { "aavgapi.exe", "avg" },
            { "aawtray.exe", "疑似杀软进程" },
            { "AAWTray.exe", "疑似杀软进程" },
            { "ackwin32.exe", "疑似杀软进程" },
            { "ad-aware.exe", "疑似杀软进程" },
            { "Ad-Aware.exe", "疑似杀软进程" },
            { "ad-watch.exe", "Lavasoft杀毒" },
            { "adam.exe", "绿鹰安全精灵" },
            { "adaware.exe", "疑似杀软进程" },
            { "ADVCHK.exe", "Norton AntiVirus" },
            { "advchk.exe", "norton antivirus" },
            { "advxdwin.exe", "疑似杀软进程" },
            { "afwServ.exe", "Avast Antivirus" },
            { "afwserv.exe", "avast antivirus" },
            { "agb.exe", "安天防线" },
            { "AGB.exe", "疑似杀软进程" },
            { "agentsvr.exe", "疑似杀软进程" },
            { "agentw.exe", "疑似杀软进程" },
            { "ahprocmonserver.exe", "安天防线" },
            { "AHPROCMONSERVER.exe", "疑似杀软进程" },
            { "AIRDEFENSE.exe", "AirDefense" },
            { "airdefense.exe", "airdefense" },
            { "akrnl.exe", "疑似杀软进程" },
            { "AKRNL.exe", "疑似杀软进程" },
            { "alertsvc.exe", "Norton AntiVirus" },
            { "ALERTSVC.exe", "Norton AntiVirus" },
            { "alevir.exe", "疑似杀软进程" },
            { "aliyundun.exe", "阿里云云盾" },
            { "AliYunDun.exe", "阿里云云盾" },
            { "alogserv.exe", "McAfee VirusScan" },
            { "amazon-ssm-agent.exe", "亚马逊EC2实例SSM代理" },
            { "AMON.exe", "Tiny Personal Firewall" },
            { "amon.exe", "tiny personal firewall" },
            { "amon9x.exe", "疑似杀软进程" },
            { "ananwidget.exe", "墨者安全专家" },
            { "anti-trojan.exe", "Anti-Trojan Elite" },
            { "antivir.exe", "疑似杀软进程" },
            { "ANTIVIR.exe", "疑似杀软进程" },
            { "antivirus.exe", "疑似杀软进程" },
            { "ants.exe", "疑似杀软进程" },
            { "AnyDesk.exe", "AnyDesk" },
            { "apimonitor.exe", "疑似杀软进程" },
            { "aplica32.exe", "疑似杀软进程" },
            { "apvxdwin.exe", "疑似杀软进程" },
            { "APVXDWIN.exe", "疑似杀软进程" },
            { "arcatasksservice.exe", "arcavir杀毒" },
            { "ArcaTasksService.exe", "ArcaVir杀毒" },
            { "armor2net.exe", "疑似杀软进程" },
            { "ARMOR2NET.exe", "疑似杀软进程" },
            { "arr.exe", "Application Request Route" },
            { "ash.exeexe.exe", "疑似杀软进程" },
            { "ASH.exeexe.exe", "疑似杀软进程" },
            { "ashdisp.exe", "avast网络安全" },
            { "ashDisp.exe", "Avast网络安全" },
            { "ashenhcd.exe", "疑似杀软进程" },
            { "ASHENHCD.exe", "疑似杀软进程" },
            { "ASHMAISV.exe", "Alwil" },
            { "ashmaisv.exe", "alwil" },
            { "ashpopwz.exe", "疑似杀软进程" },
            { "ASHPOPWZ.exe", "疑似杀软进程" },
            { "ASHSERV.exe", "Avast Anti-virus" },
            { "ashserv.exe", "avast anti-virus" },
            { "ASHSIMPL.exe", "AVAST!VirusCleaner" },
            { "ashsimpl.exe", "avast!viruscleaner" },
            { "ashskpck.exe", "疑似杀软进程" },
            { "ASHSKPCK.exe", "疑似杀软进程" },
            { "ASHWEBSV.exe", "Avast" },
            { "ashwebsv.exe", "avast" },
            { "ast.exe", "超级巡警" },
            { "AST.exe", "超级巡警" },
            { "ASWSCAN.exe", "Avast" },
            { "aswscan.exe", "avast" },
            { "ASWUPDSV.exe", "Avast" },
            { "aswupdsv.exe", "avast" },
            { "atcon.exe", "疑似杀软进程" },
            { "atguard.exe", "AntiVir" },
            { "atro55en.exe", "疑似杀软进程" },
            { "atupdater.exe", "疑似杀软进程" },
            { "atwatch.exe", "Mustek" },
            { "au.exe", "NSIS" },
            { "aupdate.exe", "Symantec" },
            { "auto-protect.nav80try.exe", "疑似杀软进程" },
            { "autodown.exe", "AntiVirus AutoUpdater" },
            { "autotrace.exe", "疑似杀软进程" },
            { "autoupdate.exe", "疑似杀软进程" },
            { "avastui.exe", "avast!5主程序" },
            { "AvastUI.exe", "Avast!5主程序" },
            { "avcenter.exe", "Avira(小红伞)" },
            { "avciman.exe", "熊猫卫士" },
            { "AVCIMAN.exe", "疑似杀软进程" },
            { "AVCONSOL.exe", "McAfee" },
            { "avconsol.exe", "McAfee" },
            { "ave32.exe", "疑似杀软进程" },
            { "avengine.exe", "熊猫卫士" },
            { "AVENGINE.exe", "疑似杀软进程" },
            { "AVESVC.exe", "Avira AntiVir Security Service" },
            { "avesvc.exe", "avira antivir security service" },
            { "aveval.exe", "疑似杀软进程" },
            { "AVEVAL.exe", "疑似杀软进程" },
            { "avevl32.exe", "疑似杀软进程" },
            { "AVEVL32.exe", "疑似杀软进程" },
            { "avg.exe", "AVG Anti-Virus" },
            { "AVGAM.exe", "AVG" },
            { "avgam.exe", "avg" },
            { "avgaurd.exe", "Avira Antivir" },
            { "AVGCC.exe", "AVG" },
            { "avgcc.exe", "avg" },
            { "AVGCC32.exe", "AVG" },
            { "avgcc32.exe", "AVG" },
            { "AVGCHSVX.exe", "AVG" },
            { "avgchsvx.exe", "avg" },
            { "avgcsrvx", "avg" },
            { "AVGCSRVX", "AVG" },
            { "avgcsrvx.exe", "疑似杀软进程" },
            { "AVGCSRVX.exe", "疑似杀软进程" },
            { "AVGCTRL.exe", "AVG" },
            { "avgctrl.exe", "AVG" },
            { "AVGEMC.exe", "AVG" },
            { "avgemc.exe", "AVG" },
            { "AVGFWSRV.exe", "AVG" },
            { "avgfwsrv.exe", "avg" },
            { "AVGNSX.exe", "AVG" },
            { "avgnsx.exe", "avg" },
            { "avgnt.exe", "Avira(小红伞)" },
            { "AVGNTMGR.exe", "AVG" },
            { "avgntmgr.exe", "avg" },
            { "avgrsx.exe", "AVG" },
            { "avgserv.exe", "AVG" },
            { "AVGSERV.exe", "AVG" },
            { "avgserv9.exe", "AVG" },
            { "AVGTRAY.exe", "AVG" },
            { "avgtray.exe", "avg" },
            { "avguard.exe", "Avira(小红伞)" },
            { "AVGUPSVC.exe", "AVG" },
            { "avgupsvc.exe", "avg" },
            { "avgw.exe", "AVG" },
            { "avgwdsvc.exe", "AVG杀毒" },
            { "AVINITNT.exe", "Command AntiVirus for NT Server" },
            { "avinitnt.exe", "command antivirus for nt server" },
            { "avira.exe", "小红伞杀毒" },
            { "AVIRA.exe", "疑似杀软进程" },
            { "avk.exe", "antiviruskit" },
            { "AVK.exe", "GData" },
            { "avkpop.exe", "G DATA SOFTWARE AG" },
            { "AVKSERV.exe", "疑似杀软进程" },
            { "avkserv.exe", "G DATA SOFTWARE AG" },
            { "avkservice.exe", "G DATA SOFTWARE AG" },
            { "AVKSERVICE.exe", "疑似杀软进程" },
            { "avkwctl.exe", "疑似杀软进程" },
            { "AVKWCTL.exe", "疑似杀软进程" },
            { "avkwctl9.exe", "G DATA SOFTWARE AG" },
            { "avltmain.exe", "Panda Software Aplication" },
            { "avnt.exe", "H+BEDV Datentechnik GmbH" },
            { "avp.exe", "Kaspersky" },
            { "AVP32.exe", "疑似杀软进程" },
            { "avp32.exe", "Kaspersky Anti-Virus" },
            { "avpcc.exe", "Kaspersky AntiVirus" },
            { "AVPCC.exe", "Kaspersky" },
            { "avpdos32.exe", "Kaspersky AntiVirus" },
            { "avpm.exe", "Kaspersky AntiVirus" },
            { "AVPM.exe", "Kaspersky" },
            { "avptc32.exe", "Kaspersky AntiVirus" },
            { "avpupd.exe", "Kaspersky AntiVirus" },
            { "AVSCHED32.exe", "H+BEDV" },
            { "avsched32.exe", "h+bedv" },
            { "AVSERVER.exe", "Kerio MailServer" },
            { "avserver.exe", "kerio mailserver" },
            { "AVSYNMGR.exe", "McAfee" },
            { "avsynmgr.exe", "McAfee" },
            { "avwatchservice.exe", "virusfighter杀毒" },
            { "AVWatchService.exe", "VIRUSfighter杀毒" },
            { "avwin.exe", "H+BEDV" },
            { "avwin95.exe", "疑似杀软进程" },
            { "avwinnt.exe", "疑似杀软进程" },
            { "avwupd.exe", "疑似杀软进程" },
            { "avwupd32.exe", "疑似杀软进程" },
            { "AVWUPD32.exe", "疑似杀软进程" },
            { "avwupsrv.exe", "h+bedv" },
            { "AVWUPSRV.exe", "H+BEDV" },
            { "avxmonitor.exe", "疑似杀软进程" },
            { "AVXMONITOR.exe", "疑似杀软进程" },
            { "avxmonitor9x.exe", "疑似杀软进程" },
            { "avxmonitornt.exe", "疑似杀软进程" },
            { "avxquar.exe", "疑似杀软进程" },
            { "AVXQUAR.exe", "疑似杀软进程" },
            { "AVZ.exe", "AVZ" },
            { "avz.exe", "avz" },
            { "awrem32.exe", "pcanywhere" },
            { "ayagent.exe", "韩国胶囊" },
            { "AYAgent.exe", "韩国胶囊" },
            { "backweb.exe", "疑似杀软进程" },
            { "baiduansvx.exe", "百度卫士-主进程" },
            { "baidusd.exe", "百度杀毒-主程序" },
            { "BaiduSd.exe", "百度杀毒-主程序" },
            { "baidusdsvc.exe", "百度杀毒-服务进程" },
            { "BaiduSdSvc.exe", "百度杀毒-服务进程" },
            { "baidusdtray.exe", "百度杀毒-托盘进程" },
            { "BaiduSdTray.exe", "百度杀毒-托盘进程" },
            { "BaradAgent.exe", "腾讯云-安全监控组件" },
            { "bargains.exe", "Exact Advertising SpyWare" },
            { "bd_professional.exe", "疑似杀软进程" },
            { "bddownloader.exe", "百度卫士" },
            { "BDSWITCH.exe", "BitDefender Module" },
            { "bdswitch.exe", "bitdefender module" },
            { "beacon.exe", "CobaltStrike 肉鸡" },
            { "beagle.exe", "Avast" },
            { "beikesan.exe", "贝壳云安全" },
            { "belt.exe", "疑似杀软进程" },
            { "bidef.exe", "疑似杀软进程" },
            { "bidserver.exe", "疑似杀软进程" },
            { "bipcp.exe", "疑似杀软进程" },
            { "bipcpevalsetup.exe", "疑似杀软进程" },
            { "bisp.exe", "疑似杀软进程" },
            { "bitdefender.exe", "疑似杀软进程" },
            { "BITDEFENDER.exe", "疑似杀软进程" },
            { "bkavservice.exe", "bkav杀毒" },
            { "BKavService.exe", "Bkav杀毒" },
            { "BLACKD.exe", "BlackICE" },
            { "blackd.exe", "BlackICE" },
            { "blackice.exe", "BlackICE" },
            { "BLACKICE.exe", "疑似杀软进程" },
            { "blink.exe", "micromedia" },
            { "blss.exe", "CBlaster" },
            { "bootconf.exe", "疑似杀软进程" },
            { "bootwarn.exe", "Symantec" },
            { "borg2.exe", "疑似杀软进程" },
            { "bpc.exe", "Grokster" },
            { "brasil.exe", "Exact Advertising" },
            { "bs120.exe", "疑似杀软进程" },
            { "bundle.exe", "疑似杀软进程" },
            { "bvt.exe", "疑似杀软进程" },
            { "cafix.exe", "疑似杀软进程" },
            { "CAFIX.exe", "疑似杀软进程" },
            { "ccapp.exe", "SymantecNorton" },
            { "ccevtmgr.exe", "symantec" },
            { "CCEVTMGR.exe", "Symantec" },
            { "ccpxysvc.exe", "疑似杀软进程" },
            { "ccregvfy.exe", "norton杀毒软件" },
            { "ccRegVfy.exe", "Norton杀毒软件自身完整性检查程序" },
            { "ccsetmgr.exe", "赛门铁克" },
            { "ccSetMgr.exe", "赛门铁克" },
            { "ccsvchst.exe", "norton杀毒" },
            { "ccSvcHst.exe", "Norton杀毒" },
            { "cdp.exe", "CyberLink Corp." },
            { "cfd.exe", "Motive Communications" },
            { "cfgwiz.exe", "Norton AntiVirus" },
            { "cfiadmin.exe", "疑似杀软进程" },
            { "cfiaudit.exe", "疑似杀软进程" },
            { "CFIAUDIT.exe", "疑似杀软进程" },
            { "cfinet.exe", "疑似杀软进程" },
            { "cfinet32.exe", "疑似杀软进程" },
            { "CFP.exe", "COMODO" },
            { "cfp.exe", "comodo" },
            { "cfpconfig.exe", "疑似杀软进程" },
            { "CFPCONFIG.exe", "疑似杀软进程" },
            { "chrome.exe", "Google Chrome" },
            { "cksoftshiedantivirus4.exe", "shield antivirus杀毒" },
            { "CKSoftShiedAntivirus4.exe", "Shield Antivirus杀毒" },
            { "clamtray.exe", "疑似杀软进程" },
            { "CLAMTRAY.exe", "疑似杀软进程" },
            { "CLAMWIN.exe", "ClamWin Portable" },
            { "clamwin.exe", "clamwin portable" },
            { "Clash for Windows.exe", "Clash for Windows" },
            { "clash-win64.exe", "Clash" },
            { "claw95.exe", "疑似杀软进程" },
            { "claw95cf.exe", "疑似杀软进程" },
            { "clean.exe", "windows流氓软件清理大师" },
            { "cleaner.exe", "windows流氓软件清理大师" },
            { "cleaner3.exe", "windows流氓软件清理大师" },
            { "cleaner8.exe", "The Cleaner杀毒" },
            { "cleanpc.exe", "windows流氓软件清理大师" },
            { "cleanup.exe", "McAfee" },
            { "click.exe", "疑似杀软进程" },
            { "CloudHelper.exe", "安全狗/云视通" },
            { "cloudmusic.exe", "网易云音乐" },
            { "cmctrayicon.exe", "cmc杀毒" },
            { "CMCTrayIcon.exe", "CMC杀毒" },
            { "cmdagent.exe", "McAfee" },
            { "cmesys.exe", "疑似杀软进程" },
            { "cmgrdian.exe", "疑似杀软进程" },
            { "cmon016.exe", "疑似杀软进程" },
            { "Code.exe", "Visual Studio Code" },
            { "connectionmonitor.exe", "疑似杀软进程" },
            { "coranticontrolcenter32.exe", "coranti2012杀毒" },
            { "CorantiControlCenter32.exe", "Coranti2012杀毒" },
            { "cpd.exe", "McAfee" },
            { "cpf.exe", "Comodo" },
            { "cpf9x206.exe", "疑似杀软进程" },
            { "cpfnt206.exe", "疑似杀软进程" },
            { "ctrl.exe", "疑似杀软进程" },
            { "CUREIT.exe", "DrWeb CureIT" },
            { "cureit.exe", "drweb cureit" },
            { "cv.exe", "疑似杀软进程" },
            { "cwnb181.exe", "疑似杀软进程" },
            { "cwntdwmo.exe", "疑似杀软进程" },
            { "d_manage.exe", "D盾" },
            { "d_safe_manage.exe", "d盾" },
            { "D_Safe_Manage.exe", "D盾" },
            { "datemanager.exe", "疑似杀软进程" },
            { "dcomx.exe", "疑似杀软进程" },
            { "defalert.exe", "Symantec" },
            { "DEFENDERDAEMON.exe", "ShadowDefender" },
            { "defenderdaemon.exe", "shadowdefender" },
            { "defscangui.exe", "Symantec" },
            { "defwatch.exe", "Norton Antivirus" },
            { "DEFWATCH.exe", "Norton Antivirus" },
            { "deputy.exe", "疑似杀软进程" },
            { "DingTalk.exe", "钉钉" },
            { "divx.exe", "疑似杀软进程" },
            { "dllcache.exe", "疑似杀软进程" },
            { "dllreg.exe", "疑似杀软进程" },
            { "doors.exe", "疑似杀软进程" },
            { "dpf.exe", "疑似杀软进程" },
            { "dpfsetup.exe", "疑似杀软进程" },
            { "dpps2.exe", "PanicWare" },
            { "drvirus.exe", "疑似杀软进程" },
            { "DRVIRUS.exe", "疑似杀软进程" },
            { "DRWADINS.exe", "Dr.Web" },
            { "drwadins.exe", "dr.web" },
            { "drwatson.exe", "疑似杀软进程" },
            { "DRWEB.exe", "Dr.Web" },
            { "drweb.exe", "dr.web" },
            { "drweb32.exe", "疑似杀软进程" },
            { "drwebupw.exe", "疑似杀软进程" },
            { "dssagent.exe", "Broderbund" },
            { "dub.exe", "在爆破" },
            { "DUB.exe", "在爆破" },
            { "dukto.exe", "dukto" },
            { "dvp95.exe", "疑似杀软进程" },
            { "dvp95_0.exe", "疑似杀软进程" },
            { "dwebio.exe", "疑似杀软进程" },
            { "DWEBIO.exe", "疑似杀软进程" },
            { "dwebllio.exe", "疑似杀软进程" },
            { "DWEBLLIO.exe", "疑似杀软进程" },
            { "ecengine.exe", "疑似杀软进程" },
            { "edr_agent.exe", "深信服EDR Agent" },
            { "edr_monitor.exe", "深信服EDR Agent" },
            { "edr_sec_plan.exe", "深信服EDR Agent" },
            { "efpeadm.exe", "疑似杀软进程" },
            { "egui.exe", "ESET NOD32" },
            { "eguiproxy.exe", "eset nod32" },
            { "eguiProxy.exe", "ESET NOD32" },
            { "ekrn.exe", "ESET NOD32" },
            { "emet_agent.exe", "EMET" },
            { "emet_service.exe", "EMET" },
            { "emsw.exe", "Alset Inc" },
            { "engineserver.exe", "McAfee" },
            { "ent.exe", "疑似杀软进程" },
            { "esafe.exe", "疑似杀软进程" },
            { "esav.exe", "启明星辰天珣edr agent" },
            { "ESAV.exe", "启明星辰天珣EDR Agent" },
            { "escanh95.exe", "疑似杀软进程" },
            { "ESCANH95.exe", "疑似杀软进程" },
            { "escanhnt.exe", "疑似杀软进程" },
            { "ESCANHNT.exe", "疑似杀软进程" },
            { "escanv95.exe", "疑似杀软进程" },
            { "escc.exe", "启明星辰天珣edr agent" },
            { "ESCC.exe", "启明星辰天珣EDR Agent" },
            { "escccontrol.exe", "启明星辰天珣edr agent" },
            { "ESCCControl.exe", "启明星辰天珣EDR Agent" },
            { "esccindex.exe", "启明星辰天珣edr agent" },
            { "ESCCIndex.exe", "启明星辰天珣EDR Agent" },
            { "espwatch.exe", "疑似杀软进程" },
            { "ethereal.exe", "RationalClearCase" },
            { "etrustcipe.exe", "疑似杀软进程" },
            { "Everything.exe", "Everything 搜索" },
            { "evpn.exe", "疑似杀软进程" },
            { "EWIDOCTRL.exe", "Ewido Security Suite" },
            { "ewidoctrl.exe", "ewido security suite" },
            { "exantivirus-cnet.exe", "疑似杀软进程" },
            { "exe.avxw.exe", "疑似杀软进程" },
            { "expert.exe", "疑似杀软进程" },
            { "explore.exe", "疑似杀软进程" },
            { "EZANTIVIRUSREGISTRATIONCHECK.exe", "e-Trust Antivirus" },
            { "ezantivirusregistrationcheck.exe", "e-trust antivirus" },
            { "f-agnt95.exe", "疑似杀软进程" },
            { "F-AGNT95.exe", "疑似杀软进程" },
            { "f-prot.exe", "f-prot antivirus" },
            { "F-PROT.exe", "F-Prot AntiVirus" },
            { "f-prot95.exe", "疑似杀软进程" },
            { "f-sched.exe", "疑似杀软进程" },
            { "F-SCHED.exe", "疑似杀软进程" },
            { "f-secure.exe", "冰岛" },
            { "f-stopw.exe", "疑似杀软进程" },
            { "F-STOPW.exe", "疑似杀软进程" },
            { "fameh32.exe", "F-Secure" },
            { "FAMEH32.exe", "疑似杀软进程" },
            { "fast.exe", "FastUsr" },
            { "fcag.exe", "McAfee" },
            { "fcagate.exe", "McAfee" },
            { "fcags.exe", "McAfee" },
            { "fcagswd.exe", "McAfee" },
            { "fch32.exe", "F-Secure" },
            { "fih32.exe", "F-Secure" },
            { "filemon.exe", "疑似杀软进程" },
            { "FILEMON.exe", "疑似杀软进程" },
            { "FileZilla Server.exe", "filezilla server" },
            { "filezilla.exe", "filezilla client" },
            { "finalshell.exe", "finalshell终端管理" },
            { "findviru.exe", "F-Secure" },
            { "firefox.exe", "Firefox" },
            { "firesvc.exe", "McAfee" },
            { "firetray.exe", "McAfee" },
            { "firewall.exe", "AshampooSoftware" },
            { "FIREWALL.exe", "AshampooSoftware" },
            { "fnrb32.exe", "F-Secure" },
            { "forticlient.exe", "疑似杀软进程" },
            { "FORTICLIENT.exe", "疑似杀软进程" },
            { "fortiscan.exe", "疑似杀软进程" },
            { "FORTISCAN.exe", "疑似杀软进程" },
            { "fortitray.exe", "飞塔" },
            { "FortiTray.exe", "飞塔" },
            { "fp-win.exe", "F-Prot Antivirus OnDemand" },
            { "fp-win_trial.exe", "疑似杀软进程" },
            { "fpavserver.exe", "疑似杀软进程" },
            { "FPAVSERVER.exe", "疑似杀软进程" },
            { "fprot.exe", "疑似杀软进程" },
            { "FPROTTRAY.exe", "F-PROT Antivirus" },
            { "fprottray.exe", "f-prot antivirus" },
            { "FPWIN.exe", "Verizon" },
            { "fpwin.exe", "verizon" },
            { "frameworkservice.exe", "mcafee" },
            { "Frameworkservice.exe", "McAfee" },
            { "FRESHCLAM.exe", "ClamAV" },
            { "freshclam.exe", "clamav" },
            { "frminst.exe", "McAfee" },
            { "frpc.exe", "frpc" },
            { "frps.exe", "frps" },
            { "frw.exe", "疑似杀软进程" },
            { "fsaa.exe", "F-Secure" },
            { "fsav.exe", "F-Secure" },
            { "FSAV32.exe", "F-Secure" },
            { "fsav32.exe", "F-Secure" },
            { "fsav530stbyb.exe", "F-Secure" },
            { "fsav530wtbyb.exe", "F-Secure" },
            { "fsav95.exe", "F-Secure" },
            { "fsavgui.exe", "F-Secure杀毒" },
            { "FSBWSYS.exe", "F-secure" },
            { "fsbwsys.exe", "f-secure" },
            { "FSDFWD.exe", "F-Secure" },
            { "fsdfwd.exe", "f-secure" },
            { "fsgk32.exe", "F-Secure" },
            { "FSGK32.exe", "F-Secure" },
            { "FSGK32ST.exe", "F-Secure" },
            { "fsgk32st.exe", "f-secure" },
            { "fsguiexe.exe", "疑似杀软进程" },
            { "FSGUIEXE.exe", "疑似杀软进程" },
            { "fsm32.exe", "F-Secure" },
            { "FSMA32.exe", "F-Secure" },
            { "fsma32.exe", "F-Secure" },
            { "FSMB32.exe", "F-Secure" },
            { "fsmb32.exe", "F-Secure" },
            { "fspex.exe", "疑似杀软进程" },
            { "FSPEX.exe", "疑似杀软进程" },
            { "FSSM32.exe", "F-Secure" },
            { "fssm32.exe", "f-secure" },
            { "fyfirewall.exe", "风云防火墙" },
            { "FYFireWall.exe", "风云防火墙" },
            { "G6FTPServer.exe", "Gene6 FTP Server" },
            { "G6FTPTray.exe", "Gene6 FTP" },
            { "gator.exe", "疑似杀软进程" },
            { "gbmenu.exe", "疑似杀软进程" },
            { "gbpoll.exe", "疑似杀软进程" },
            { "gcasdtserv.exe", "疑似杀软进程" },
            { "GCASDTSERV.exe", "疑似杀软进程" },
            { "gcasserv.exe", "疑似杀软进程" },
            { "GCASSERV.exe", "疑似杀软进程" },
            { "geek.exe", "geek" },
            { "generics.exe", "疑似杀软进程" },
            { "gg.exe", "巨盾网游安全盾" },
            { "GG.exe", "巨盾网游安全盾" },
            { "giantantispyware.exe", "疑似杀软进程" },
            { "GIANTANTISPYWARE.exe", "疑似杀软进程" },
            { "gmt.exe", "疑似杀软进程" },
            { "gov_defence_daemon.exe", "云锁" },
            { "gov_defence_service.exe", "云锁" },
            { "gse_win_agent.exe", "蓝鲸Agent" },
            { "gse_win_daemon.exe", "蓝鲸Agent" },
            { "guard.exe", "ewido" },
            { "guarddog.exe", "ewido" },
            { "guardgui.exe", "网游保镖" },
            { "GUARDGUI.exe", "疑似杀软进程" },
            { "GUARDNT.exe", "IKARUS" },
            { "guardnt.exe", "ikarus" },
            { "guardxkickoff.exe", "疑似杀软进程" },
            { "GUARDXKICKOFF.exe", "疑似杀软进程" },
            { "guardxservice.exe", "疑似杀软进程" },
            { "GUARDXSERVICE.exe", "疑似杀软进程" },
            { "hacktracersetup.exe", "疑似杀软进程" },
            { "hbinst.exe", "疑似杀软进程" },
            { "hbsrv.exe", "疑似杀软进程" },
            { "hipsdaemon.exe", "火绒" },
            { "HipsDaemon.exe", "火绒" },
            { "hipstray.exe", "火绒" },
            { "HipsTray.exe", "火绒" },
            { "hipsvc.exe", "McAfee" },
            { "hotactio.exe", "疑似杀软进程" },
            { "hotpatch.exe", "疑似杀软进程" },
            { "hregmon.exe", "疑似杀软进程" },
            { "HREGMON.exe", "疑似杀软进程" },
            { "hrres.exe", "疑似杀软进程" },
            { "HRRES.exe", "疑似杀软进程" },
            { "hsockpe.exe", "疑似杀软进程" },
            { "HSOCKPE.exe", "疑似杀软进程" },
            { "htlog.exe", "疑似杀软进程" },
            { "htpatch.exe", "Silicon Integrated Systems Corporation" },
            { "hupdate.exe", "疑似杀软进程" },
            { "HUPDATE.exe", "疑似杀软进程" },
            { "hwpe.exe", "疑似杀软进程" },
            { "hws.exe", "护卫神" },
            { "hws_ui.exe", "护卫神" },
            { "hwsd.exe", "护卫神" },
            { "hwspanel.exe", "护卫神" },
            { "HwsPanel.exe", "护卫神" },
            { "hxdl.exe", "疑似杀软进程" },
            { "hxiul.exe", "疑似杀软进程" },
            { "iamapp.exe", "Symantec" },
            { "IAMAPP.exe", "Symantec" },
            { "IAMSERV.exe", "疑似杀软进程" },
            { "iamserv.exe", "Symantec" },
            { "iamstats.exe", "Symantec" },
            { "ibmasn.exe", "疑似杀软进程" },
            { "ibmavsp.exe", "疑似杀软进程" },
            { "icload95.exe", "疑似杀软进程" },
            { "ICLOAD95.exe", "疑似杀软进程" },
            { "icloadnt.exe", "疑似杀软进程" },
            { "ICLOADNT.exe", "疑似杀软进程" },
            { "icmon.exe", "疑似杀软进程" },
            { "ICMON.exe", "疑似杀软进程" },
            { "icssuppnt.exe", "疑似杀软进程" },
            { "ICSSUPPNT.exe", "疑似杀软进程" },
            { "icsupp95.exe", "疑似杀软进程" },
            { "ICSUPP95.exe", "疑似杀软进程" },
            { "icsuppnt.exe", "疑似杀软进程" },
            { "ICSUPPNT.exe", "疑似杀软进程" },
            { "ida.exe", "ida" },
            { "ida64.exe", "ida64" },
            { "idea64.exe", "IDEA工具" },
            { "idle.exe", "疑似杀软进程" },
            { "iedll.exe", "疑似杀软进程" },
            { "iedriver.exe", "Urlblaze.com" },
            { "iface.exe", "Panda Antivirus Module" },
            { "ifw2000.exe", "疑似杀软进程" },
            { "Imagine.exe", "Imagine" },
            { "inetlnfo.exe", "疑似杀软进程" },
            { "inetupd.exe", "疑似杀软进程" },
            { "INETUPD.exe", "疑似杀软进程" },
            { "infus.exe", "Infus Dialer" },
            { "infwin.exe", "Msviewparasite" },
            { "init.exe", "疑似杀软进程" },
            { "INOCIT.exe", "eTrust" },
            { "inocit.exe", "etrust" },
            { "INORPC.exe", "eTrust" },
            { "inorpc.exe", "etrust" },
            { "INORT.exe", "eTrust" },
            { "inort.exe", "etrust" },
            { "INOTASK.exe", "eTrust" },
            { "inotask.exe", "etrust" },
            { "INOUPTNG.exe", "eTrust" },
            { "inouptng.exe", "etrust" },
            { "intdel.exe", "Inet Delivery" },
            { "intren.exe", "疑似杀软进程" },
            { "iomon98.exe", "疑似杀软进程" },
            { "IOMON98.exe", "疑似杀软进程" },
            { "iparmor.exe.exe", "木马克星" },
            { "Iparmor.exe.exe", "木马克星" },
            { "iptray.exe", "Immunet杀毒" },
            { "ISAFE.exe", "eTrust" },
            { "isafe.exe", "etrust" },
            { "isatray.exe", "疑似杀软进程" },
            { "ISATRAY.exe", "疑似杀软进程" },
            { "istsvc.exe", "疑似杀软进程" },
            { "jammer.exe", "疑似杀软进程" },
            { "java.exe", "java" },
            { "jdbgmrg.exe", "疑似杀软进程" },
            { "jedi.exe", "疑似杀软进程" },
            { "k7tsecurity.exe", "k7杀毒" },
            { "K7TSecurity.exe", "K7杀毒" },
            { "KAV.exe", "Kaspersky" },
            { "kav.exe", "kaspersky" },
            { "kavlite40eng.exe", "疑似杀软进程" },
            { "KAVMM.exe", "Kaspersky" },
            { "kavmm.exe", "kaspersky" },
            { "kavpers40eng.exe", "疑似杀软进程" },
            { "KAVPF.exe", "Kaspersky" },
            { "kavpf.exe", "kaspersky" },
            { "KAVPFW.exe", "Kaspersky" },
            { "kavpfw.exe", "kaspersky" },
            { "KAVSTART.exe", "Kaspersky" },
            { "kavstart.exe", "kaspersky" },
            { "KAVSVC.exe", "Kaspersky" },
            { "kavsvc.exe", "kaspersky" },
            { "KAVSVCUI.exe", "Kaspersky" },
            { "kavsvcui.exe", "kaspersky" },
            { "kazza.exe", "Kapersky" },
            { "keenvalue.exe", "EUNIVERSE INC" },
            { "kerio-pf-213-en-win.exe", "疑似杀软进程" },
            { "kerio-wrl-421-en-win.exe", "疑似杀软进程" },
            { "kerio-wrp-421-en-win.exe", "疑似杀软进程" },
            { "kernel32.exe", "疑似杀软进程" },
            { "killprocesssetup161.exe", "疑似杀软进程" },
            { "kmailmon.exe", "金山毒霸" },
            { "KMAILMON.exe", "疑似杀软进程" },
            { "knsdtray.exe", "可牛杀毒" },
            { "kpfwtray.exe", "金山网镖" },
            { "ksafe.exe", "金山卫士" },
            { "ksafesvc.exe", "金山毒霸" },
            { "KSafeSvc.exe", "疑似杀软进程" },
            { "ksafetray.exe", "金山毒霸" },
            { "KSafeTray.exe", "疑似杀软进程" },
            { "kswebshield.exe", "金山网盾" },
            { "KSWebShield.exe", "金山网盾" },
            { "kvmonxp.exe", "江民杀毒" },
            { "KvMonXP.exe", "江民杀毒" },
            { "kwatch.exe", "金山毒霸" },
            { "KWatch.exe", "疑似杀软进程" },
            { "kxetray.exe", "金山毒霸" },
            { "launcher.exe", "Intercort Systems" },
            { "ldnetmon.exe", "疑似杀软进程" },
            { "ldnews.exe", "LDPlayer - 适用于 PC 的轻量级快速 Android 模拟器" },
            { "ldpro.exe", "疑似杀软进程" },
            { "ldpromenu.exe", "疑似杀软进程" },
            { "ldscan.exe", "Windows Trojans Inspector" },
            { "lghub_updater.exe", "罗技鼠标软件" },
            { "lnetinfo.exe", "疑似杀软进程" },
            { "loader.exe", "疑似杀软进程" },
            { "localnet.exe", "疑似杀软进程" },
            { "lockdown.exe", "疑似杀软进程" },
            { "lockdown2000.exe", "疑似杀软进程" },
            { "LogiOptions.exe", "LogiOptions" },
            { "lookout.exe", "疑似杀软进程" },
            { "lordpe.exe", "疑似杀软进程" },
            { "lsetup.exe", "疑似杀软进程" },
            { "Lsf.exe", "联想电脑管家" },
            { "luall.exe", "Symantec" },
            { "luau.exe", "Symantec" },
            { "lucomserver.exe", "Norton" },
            { "luinit.exe", "疑似杀软进程" },
            { "luspt.exe", "疑似杀软进程" },
            { "macompatsvc.exe", "McAfee" },
            { "mamutu.exe", "疑似杀软进程" },
            { "MAMUTU.exe", "疑似杀软进程" },
            { "mapisvc32.exe", "疑似杀软进程" },
            { "masvc.exe", "McAfee" },
            { "mcafeefire.exe", "McAfee" },
            { "MCAGENT.exe", "McAfee" },
            { "mcagent.exe", "McAfee" },
            { "mcamnsvc.exe", "McAfee" },
            { "mcmnhdlr.exe", "McAfee" },
            { "MCMNHDLR.exe", "McAfee" },
            { "MCREGWIZ.exe", "McAfee" },
            { "mcregwiz.exe", "mcafee" },
            { "mcscript.exe", "McAfee" },
            { "mcscript_inuse.exe", "McAfee" },
            { "mcshield.exe", "McAfee" },
            { "Mcshield.exe", "McAfee" },
            { "mctary.exe", "McAfee" },
            { "mctool.exe", "McAfee" },
            { "mctray.exe", "McAfee" },
            { "mcupdate.exe", "McAfee" },
            { "MCUPDATE.exe", "McAfee" },
            { "mcvsrte.exe", "McAfee" },
            { "mcvsshld.exe", "McAfee" },
            { "MCVSSHLD.exe", "McAfee" },
            { "md.exe", "疑似杀软进程" },
            { "mfeann.exe", "McAfee" },
            { "mfecanary.exe", "McAfee" },
            { "mfeconsole.exe", "McAfee" },
            { "mfeesp.exe", "McAfee" },
            { "mfefire.exe", "McAfee" },
            { "mfefw.exe", "McAfee" },
            { "mfemms.exe", "McAfee" },
            { "mfetp.exe", "McAfee" },
            { "mfevtps.exe", "McAfee" },
            { "mfewc.exe", "McAfee" },
            { "mfewch.exe", "McAfee" },
            { "mfin32.exe", "MyFreeInternetUpdate" },
            { "mfw2en.exe", "MyFreeInternetUpdate" },
            { "mfweng3.02d30.exe", "MyFreeInternetUpdate" },
            { "mgavrtcl.exe", "McAfee" },
            { "mgavrte.exe", "McAfee" },
            { "mghtml.exe", "McAfee" },
            { "mgui.exe", "BullGuard" },
            { "miner.exe", "流量矿石" },
            { "Miner.exe", "流量矿石" },
            { "Mini Mouse.exe", "Mini Mouse(有LFI和RCE)" },
            { "MINILOG.exe", "Zone Alarm" },
            { "minilog.exe", "Zone Labs Inc" },
            { "mmod.exe", "EzulaInc" },
            { "mongoosagui.exe", "mongoosa杀毒" },
            { "MongoosaGUI.exe", "Mongoosa杀毒" },
            { "monitor.exe", "疑似杀软进程" },
            { "moolive.exe", "疑似杀软进程" },
            { "mostat.exe", "WurldMediaInc" },
            { "mpfagent.exe", "McAfee" },
            { "mpfservice.exe", "McAfee" },
            { "mpftray.exe", "McAfee" },
            { "mpmon.exe", "微点主动防御" },
            { "MPMon.exe", "微点主动防御" },
            { "mrflux.exe", "疑似杀软进程" },
            { "msapp.exe", "疑似杀软进程" },
            { "msascui.exe", "疑似杀软进程" },
            { "MSPCManager.exe", "微软电脑管家" },
            { "MSASCui.exe", "疑似杀软进程" },
            { "msbb.exe", "疑似杀软进程" },
            { "msblast.exe", "疑似杀软进程" },
            { "mscache.exe", "Integrated Search Technologies Spyware" },
            { "msccn32.exe", "疑似杀软进程" },
            { "mscman.exe", "OdysseusMarketingInc" },
            { "msconfig.exe", "疑似杀软进程" },
            { "msdm.exe", "疑似杀软进程" },
            { "msdos.exe", "疑似杀软进程" },
            { "MsDtsSrvr.exe", "MicrosoftSQLServer" },
            { "msiexec16.exe", "疑似杀软进程" },
            { "msinfo32.exe", "疑似杀软进程" },
            { "mslaugh.exe", "疑似杀软进程" },
            { "msmgt.exe", "Total Velocity Spyware" },
            { "MsMpEng.exe", "Windows Defender" },
            { "msmpeng.exe", "Windows Defender" },
            { "msmsgri32.exe", "疑似杀软进程" },
            { "mssecess.exe", "微软杀毒" },
            { "mssmmc32.exe", "疑似杀软进程" },
            { "mssys.exe", "疑似杀软进程" },
            { "msvxd.exe", "W32/Datom-A" },
            { "mu0311ad.exe", "疑似杀软进程" },
            { "mwatch.exe", "疑似杀软进程" },
            { "MYAGTSVC.exe", "McAfee" },
            { "myagtsvc.exe", "mcafee" },
            { "MYAGTTRY.exe", "McAfee" },
            { "myagttry.exe", "mcafee" },
            { "mysqld.exe", "mysql" },
            { "n32scanw.exe", "疑似杀软进程" },
            { "naprdmgr.exe", "McAfee" },
            { "nav.exe", "Reuters Limited" },
            { "navap.navapsvc.exe", "疑似杀软进程" },
            { "navapsvc.exe", "Norton AntiVirus" },
            { "NAVAPSVC.exe", "Norton" },
            { "navapw32.exe", "Norton AntiVirus" },
            { "NAVAPW32.exe", "Norton" },
            { "navdx.exe", "疑似杀软进程" },
            { "navicat.exe", "navicat" },
            { "navlu32.exe", "norton" },
            { "NAVLU32.exe", "Norton" },
            { "navnt.exe", "疑似杀软进程" },
            { "navstub.exe", "疑似杀软进程" },
            { "NAVW32.exe", "Norton Antivirus" },
            { "navw32.exe", "Norton Antivirus" },
            { "navwnt.exe", "疑似杀软进程" },
            { "nc2000.exe", "疑似杀软进程" },
            { "ncinst4.exe", "疑似杀软进程" },
            { "ndd32.exe", "疑似杀软进程" },
            { "neomonitor.exe", "疑似杀软进程" },
            { "neowatchlog.exe", "neowatch" },
            { "NEOWATCHLOG.exe", "NeoWatch" },
            { "NEOWATCHTRAY.exe", "NeoWatch" },
            { "neowatchtray.exe", "neowatch" },
            { "netarmor.exe", "疑似杀软进程" },
            { "netd32.exe", "疑似杀软进程" },
            { "netinfo.exe", "疑似杀软进程" },
            { "netmon.exe", "疑似杀软进程" },
            { "netscanpro.exe", "疑似杀软进程" },
            { "netspyhunter-1.2.exe", "疑似杀软进程" },
            { "netstat.exe", "疑似杀软进程" },
            { "netutils.exe", "疑似杀软进程" },
            { "NISSERV.exe", "Norton" },
            { "nisserv.exe", "Norton" },
            { "NisSrv.exe", "Windows Defender" },
            { "NISUM.exe", "Norton" },
            { "nisum.exe", "Norton" },
            { "NMAIN.exe", "Norton" },
            { "nmain.exe", "Norton" },
            { "NOD32.exe", "ESET NOD32" },
            { "nod32.exe", "ESET Smart Security" },
            { "normist.exe", "疑似杀软进程" },
            { "NORMIST.exe", "疑似杀软进程" },
            { "norton_internet_secu_3.0_407.exe", "疑似杀软进程" },
            { "notstart.exe", "疑似杀软进程" },
            { "NOTSTART.exe", "疑似杀软进程" },
            { "npavtray.exe", "疑似杀软进程" },
            { "NPAVTRAY.exe", "疑似杀软进程" },
            { "npf40_tw_98_nt_me_2k.exe", "疑似杀软进程" },
            { "npfmessenger.exe", "疑似杀软进程" },
            { "npfmntor.exe", "norton杀毒软件" },
            { "NPFMntor.exe", "Norton杀毒软件相关进程" },
            { "NPFMSG.exe", "Norman个人防火墙" },
            { "npfmsg.exe", "norman个人防火墙" },
            { "NPROTECT.exe", "Symantec" },
            { "nprotect.exe", "Symantec" },
            { "npscheck.exe", "Norton" },
            { "npssvc.exe", "Norton" },
            { "nsched32.exe", "疑似杀软进程" },
            { "NSCHED32.exe", "疑似杀软进程" },
            { "NSMDTR.exe", "Norton" },
            { "nsmdtr.exe", "norton" },
            { "nspupsvc.exe", "nProtect杀毒" },
            { "nssserv.exe", "疑似杀软进程" },
            { "NSSSERV.exe", "疑似杀软进程" },
            { "nsstray.exe", "疑似杀软进程" },
            { "NSSTRAY.exe", "疑似杀软进程" },
            { "nssys32.exe", "疑似杀软进程" },
            { "nstask32.exe", "疑似杀软进程" },
            { "nsupdate.exe", "疑似杀软进程" },
            { "nt.exe", "疑似杀软进程" },
            { "ntos.exe", "疑似杀软进程" },
            { "NTOS.exe", "疑似杀软进程" },
            { "NTRTScan.exe", "趋势反病毒应用程序" },
            { "ntrtscan.exe", "疑似杀软进程" },
            { "NTRTSCAN.exe", "疑似杀软进程" },
            { "ntvdm.exe", "疑似杀软进程" },
            { "ntxconfig.exe", "疑似杀软进程" },
            { "NTXCONFIG.exe", "疑似杀软进程" },
            { "nui.exe", "疑似杀软进程" },
            { "nupgrade.exe", "疑似杀软进程" },
            { "NUPGRADE.exe", "疑似杀软进程" },
            { "NutstoreClient.exe", "坚果云" },
            { "NutstoreDriverSvc.exe", "坚果云" },
            { "NutstoreWatchDog.exe", "坚果云" },
            { "nvarch16.exe", "疑似杀软进程" },
            { "nvc95.exe", "疑似杀软进程" },
            { "nvcod.exe", "疑似杀软进程" },
            { "NVCOD.exe", "疑似杀软进程" },
            { "nvcte.exe", "疑似杀软进程" },
            { "NVCTE.exe", "疑似杀软进程" },
            { "nvcut.exe", "疑似杀软进程" },
            { "NVCUT.exe", "疑似杀软进程" },
            { "nvsvc32.exe", "疑似杀软进程" },
            { "nwinst4.exe", "疑似杀软进程" },
            { "nwservice.exe", "疑似杀软进程" },
            { "NWSERVICE.exe", "疑似杀软进程" },
            { "nwtool16.exe", "疑似杀软进程" },
            { "OFCPFWSVC.exe", "OfficeScanNT" },
            { "ofcpfwsvc.exe", "officescannt" },
            { "ollydbg.exe", "疑似杀软进程" },
            { "OneDrive.exe", "Microsoft OneDrive" },
            { "onlinent.exe", "疑似杀软进程" },
            { "ONLINENT.exe", "疑似杀软进程" },
            { "onsrvr.exe", "疑似杀软进程" },
            { "OP_MON.exe", "OutpostFirewall" },
            { "op_mon.exe", "outpostfirewall" },
            { "OpenArk64.exe", "OpenArk" },
            { "OpenVPNConnect.exe", "openvpn" },
            { "opssvc.exe", "疑似杀软进程" },
            { "OPSSVC.exe", "疑似杀软进程" },
            { "optimize.exe", "疑似杀软进程" },
            { "ostronet.exe", "疑似杀软进程" },
            { "otfix.exe", "疑似杀软进程" },
            { "outpost.exe", "Outpost Firewall" },
            { "outpostinstall.exe", "Outpost" },
            { "outpostproinstall.exe", "疑似杀软进程" },
            { "ovpnhelper_service.exe", "openvpn" },
            { "padmin.exe", "疑似杀软进程" },
            { "panixk.exe", "疑似杀软进程" },
            { "parmor.exe", "木马克星" },
            { "patch.exe", "疑似杀软进程" },
            { "patray.exe", "安博士" },
            { "pavcl.exe", "疑似杀软进程" },
            { "pavfires.exe", "熊猫卫士" },
            { "PAVFIRES.exe", "疑似杀软进程" },
            { "pavfnsvr.exe", "熊猫卫士" },
            { "PAVFNSVR.exe", "疑似杀软进程" },
            { "pavkre.exe", "熊猫卫士" },
            { "PAVKRE.exe", "疑似杀软进程" },
            { "pavprot.exe", "熊猫卫士" },
            { "PAVPROT.exe", "疑似杀软进程" },
            { "pavproxy.exe", "疑似杀软进程" },
            { "PAVPROXY.exe", "疑似杀软进程" },
            { "pavprsrv.exe", "熊猫卫士" },
            { "PAVPRSRV.exe", "疑似杀软进程" },
            { "pavsched.exe", "疑似杀软进程" },
            { "pavsrv51.exe", "熊猫卫士" },
            { "PAVSRV51.exe", "疑似杀软进程" },
            { "pavss.exe", "熊猫卫士" },
            { "PAVSS.exe", "疑似杀软进程" },
            { "pavw.exe", "疑似杀软进程" },
            { "PCCGUIDE.exe", "PC-cillin" },
            { "pccguide.exe", "pc-cillin" },
            { "PCCIOMON.exe", "PC-cillin" },
            { "pcciomon.exe", "pc-cillin" },
            { "PccNTMon.exe", "趋势 PC-cillin 反病毒套装" },
            { "PCCNTMON.exe", "PC-cillin" },
            { "pccntmon.exe", "pc-cillin" },
            { "pccpfw.exe", "趋势科技" },
            { "PCCPFW.exe", "疑似杀软进程" },
            { "pcctlcom.exe", "趋势科技" },
            { "PCCTLCOM.exe", "疑似杀软进程" },
            { "pccwin98.exe", "疑似杀软进程" },
            { "pcfwallicon.exe", "疑似杀软进程" },
            { "pcip10117_0.exe", "疑似杀软进程" },
            { "pcscan.exe", "疑似杀软进程" },
            { "PCTAV.exe", "PC Tools AntiVirus" },
            { "pctav.exe", "pc tools antivirus" },
            { "pdsetup.exe", "疑似杀软进程" },
            { "periscope.exe", "疑似杀软进程" },
            { "PERSFW.exe", "Tiny Personal Firewall" },
            { "persfw.exe", "Tiny Personal Firewall" },
            { "perswf.exe", "疑似杀软进程" },
            { "pertsk.exe", "疑似杀软进程" },
            { "PERTSK.exe", "疑似杀软进程" },
            { "pervac.exe", "疑似杀软进程" },
            { "PERVAC.exe", "疑似杀软进程" },
            { "PESTPATROL.exe", "Ikarus" },
            { "pestpatrol.exe", "ikarus" },
            { "pf2.exe", "疑似杀软进程" },
            { "pfw.exe", "天网防火墙" },
            { "pfwadmin.exe", "疑似杀软进程" },
            { "pgmonitr.exe", "PromulGate SpyWare" },
            { "php-cgi.exe", "php" },
            { "pingscan.exe", "疑似杀软进程" },
            { "platin.exe", "疑似杀软进程" },
            { "pnmsrv.exe", "疑似杀软进程" },
            { "PNMSRV.exe", "疑似杀软进程" },
            { "pop3trap.exe", "PC-cillin" },
            { "poproxy.exe", "NortonAntiVirus" },
            { "popscan.exe", "疑似杀软进程" },
            { "portdetective.exe", "疑似杀软进程" },
            { "portmonitor.exe", "疑似杀软进程" },
            { "powerscan.exe", "Integrated Search Technologies" },
            { "powershell.exe", "Windows PowerShell" },
            { "ppinupdt.exe", "疑似杀软进程" },
            { "pptbc.exe", "疑似杀软进程" },
            { "ppvstop.exe", "疑似杀软进程" },
            { "prevsrv.exe", "熊猫卫士" },
            { "PREVSRV.exe", "疑似杀软进程" },
            { "prevx.exe", "疑似杀软进程" },
            { "PREVX.exe", "疑似杀软进程" },
            { "prizesurfer.exe", "Prizesurfer" },
            { "prl_cc.exe", "Parallels Desktop 虚拟机【虚拟机程序】" },
            { "prl_tools.exe", "Parallels Tools【虚拟机程序】" },
            { "prl_tools_service.exe", "Parallels Tools【虚拟机程序】" },
            { "prmt.exe", "OpiStat" },
            { "prmvr.exe", "Adtomi" },
            { "procdump.exe", "疑似杀软进程" },
            { "processmonitor.exe", "Sysinternals" },
            { "procexplorerv1.0.exe", "疑似杀软进程" },
            { "programauditor.exe", "疑似杀软进程" },
            { "proport.exe", "疑似杀软进程" },
            { "protectx.exe", "ProtectX" },
            { "psafesystray.exe", "psafe杀毒" },
            { "PSafeSysTray.exe", "PSafe杀毒" },
            { "psimsvc.exe", "疑似杀软进程" },
            { "PSIMSVC.exe", "疑似杀软进程" },
            { "pspf.exe", "疑似杀软进程" },
            { "purge.exe", "疑似杀软进程" },
            { "qconsole.exe", "Norton AntiVirus Quarantine Console" },
            { "qhonline.exe", "疑似杀软进程" },
            { "QHONLINE.exe", "疑似杀软进程" },
            { "qhonsvc.exe", "疑似杀软进程" },
            { "QHONSVC.exe", "疑似杀软进程" },
            { "qhset.exe", "疑似杀软进程" },
            { "QHSET.exe", "疑似杀软进程" },
            { "qhwscsvc.exe", "疑似杀软进程" },
            { "QHWSCSVC.exe", "疑似杀软进程" },
            { "qqpcrtp.exe", "qq电脑管家" },
            { "QQPCRTP.exe", "QQ电脑管家" },
            { "QQPCTray.exe", "QQ电脑管家" },
            { "qqpctray.exe", "qq电脑管家" },
            { "QQProtect.exe", "QQ安全防护进程（Q盾）" },
            { "qserver.exe", "Norton Internet Security" },
            { "quhlpsvc.exe", "quick heal杀毒" },
            { "QUHLPSVC.exe", "QUICK HEAL杀毒" },
            { "r_server.exe", "radmin" },
            { "RadeonSoftware.exe", "AMD驱动软件" },
            { "rapapp.exe", "BlackICE" },
            { "rav7.exe", "疑似杀软进程" },
            { "rav7win.exe", "疑似杀软进程" },
            { "rav8win32eng.exe", "疑似杀软进程" },
            { "ravmond.exe", "瑞星杀毒" },
            { "RavMonD.exe", "瑞星杀毒" },
            { "ray.exe", "疑似杀软进程" },
            { "rb32.exe", "RapidBlaster" },
            { "rcsync.exe", "PrizeSurfer" },
            { "realmon.exe", "Realmon" },
            { "reged.exe", "疑似杀软进程" },
            { "regedit.exe", "疑似杀软进程" },
            { "regedt32.exe", "疑似杀软进程" },
            { "remupd.exe", "熊猫卫士" },
            { "rescue.exe", "疑似杀软进程" },
            { "rescue32.exe", "疑似杀软进程" },
            { "rfwmain.exe", "瑞星防火墙" },
            { "rrguard.exe", "疑似杀软进程" },
            { "rshell.exe", "疑似杀软进程" },
            { "rtvscan.exe", "诺顿杀毒" },
            { "rtvscn95.exe", "疑似杀软进程" },
            { "RTVSCN95.exe", "Real-time Virus Scanner" },
            { "rulaunch.exe", "McAfee User Interface" },
            { "run32dll.exe", "PAL PC Spy" },
            { "rundll.exe", "疑似杀软进程" },
            { "rundll16.exe", "疑似杀软进程" },
            { "ruxdll32.exe", "疑似杀软进程" },
            { "safeboxTray.exe", "疑似杀软进程" },
            { "safedog.exe", "安全狗" },
            { "SafeDogGuardCenter.exe", "安全狗" },
            { "SafeDogServerUI.exe", "安全狗" },
            { "SafeDogSiteIIS.exe", "安全狗" },
            { "SafeDogTray.exe", "安全狗" },
            { "safedogupdatecenter.exe", "安全狗" },
            { "safeweb.exe", "PSafe Tecnologia" },
            { "sahagent.exescan32.exe", "疑似杀软进程" },
            { "SALITY.exe", "疑似杀软进程" },
            { "SAPISSVC.exe", "疑似杀软进程" },
            { "SAVADMINSERVICE.exe", "SAV" },
            { "save.exe", "疑似杀软进程" },
            { "savenow.exe", "疑似杀软进程" },
            { "SAVMAIN.exe", "SAV" },
            { "savmain.exe", "sav" },
            { "SavProgress.exe", "Sophos杀毒" },
            { "SAVSCAN.exe", "SAV" },
            { "sbamsvc.exe", "vipre" },
            { "SBAMSvc.exe", "VIPRE" },
            { "sbserv.exe", "Norton Antivirus" },
            { "sc.exe", "疑似杀软进程" },
            { "scam32.exe", "疑似杀软进程" },
            { "scan32.exe", "McAfee" },
            { "scan95.exe", "疑似杀软进程" },
            { "scanningprocess.exe", "疑似杀软进程" },
            { "SCANNINGPROCESS.exe", "疑似杀软进程" },
            { "scanpm.exe", "疑似杀软进程" },
            { "scanwscs.exe", "疑似杀软进程" },
            { "SCANWSCS.exe", "疑似杀软进程" },
            { "sched.exe", "Avira(小红伞)" },
            { "scrscan.exe", "疑似杀软进程" },
            { "SDHELP.exe", "Spyware Doctor" },
            { "SDRA64.exe", "疑似杀软进程" },
            { "SecurityHealthService.exe", "Windows Defender" },
            { "SecurityHealthSystray.exe", "Windows Defender"},
            { "serv-u.exe", "server-u" },
            { "serv95.exe", "疑似杀软进程" },
            { "servudaemon.exe", "发现s-u" },
            { "ServUDaemon.exe", "发现S-U" },
            { "setup_flowprotector_us.exe", "疑似杀软进程" },
            { "setupvameeval.exe", "疑似杀软进程" },
            { "sfc.exe", "System file checker" },
            { "sgagent.exe", "腾讯云-安全监控组件" },
            { "sgssfw32.exe", "疑似杀软进程" },
            { "sh.exe", "MKS Toolkit for Win3" },
            { "ShadowsocksR-dotnet4.0.ex", "SSR" },
            { "shellspyinstall.exe", "疑似杀软进程" },
            { "shn.exe", "疑似杀软进程" },
            { "showbehind.exe", "MicroSmarts Enterprise Component" },
            { "shstat.exe", "McAfee" },
            { "SHSTAT.exe", "McAfee" },
            { "sitecli.exe", "疑似杀软进程" },
            { "SITECLI.exe", "疑似杀软进程" },
            { "smartscreen.exe", "Windows Defender" },
            { "smc.exe", "疑似杀软进程" },
            { "sms.exe", "疑似杀软进程" },
            { "smss32.exe", "疑似杀软进程" },
            { "soap.exe", "System Soap Pro" },
            { "sofi.exe", "疑似杀软进程" },
            { "sophoscleanm.exe", "sophos杀毒" },
            { "SophosCleanM.exe", "Sophos杀毒" },
            { "sophosfs.exe", "sophos杀毒" },
            { "SophosFS.exe", "Sophos杀毒" },
            { "sophoshealth.exe", "sophos杀毒" },
            { "SophosHealth.exe", "Sophos杀毒" },
            { "sophossafestore64.exe", "sophos杀毒" },
            { "SophosSafestore64.exe", "Sophos杀毒" },
            { "sophosui.exe", "sophos杀毒" },
            { "SophosUI.exe", "Sophos杀毒" },
            { "SPBBCSVC.exe", "Symantec" },
            { "spbbcsvc.exe", "symantec" },
            { "sperm.exe", "疑似杀软进程" },
            { "spf.exe", "疑似杀软进程" },
            { "sphinx.exe", "sphinx防火墙" },
            { "SPHINX.exe", "SPHINX防火墙" },
            { "SPIDERCPL.exe", "Dr.Web" },
            { "spidercpl.exe", "dr.web" },
            { "SPIDERML.exe", "Dr.Web" },
            { "spiderml.exe", "dr.web" },
            { "spidernt.exe", "Dr.web" },
            { "SPIDERUI.exe", "Dr.Web" },
            { "spiderui.exe", "dr.web" },
            { "spoler.exe", "疑似杀软进程" },
            { "spoolcv.exe", "疑似杀软进程" },
            { "spoolsv.exe", "打印机驱动程序" },
            { "spoolsv32.exe", "疑似杀软进程" },
            { "SPYBOTSD.exe", "Spybot" },
            { "spybotsd.exe", "spybot" },
            { "spywareterminatorshield.exe", "spywareterminator反间谍软件" },
            { "SpywareTerminatorShield.exe", "SpywareTerminator杀毒" },
            { "spyxx.exe", "疑似杀软进程" },
            { "SPYXX.exe", "疑似杀软进程" },
            { "srexe.exe", "疑似杀软进程" },
            { "srng.exe", "疑似杀软进程" },
            { "ss3edit.exe", "疑似杀软进程" },
            { "SS3EDIT.exe", "疑似杀软进程" },
            { "ssg_4104.exe", "疑似杀软进程" },
            { "ssgrate.exe", "疑似杀软进程" },
            { "ssm-agent-worker.exe", "亚马逊EC2实例SSM代理" },
            { "st2.exe", "疑似杀软进程" },
            { "start.exe", "疑似杀软进程" },
            { "stcloader.exe", "疑似杀软进程" },
            { "stopsignav.exe", "疑似杀软进程" },
            { "STOPSIGNAV.exe", "疑似杀软进程" },
            { "SunloginClient.exe", "向日葵客户端" },
            { "supftrl.exe", "疑似杀软进程" },
            { "support.exe", "疑似杀软进程" },
            { "supporter5.exe", "eScorcher反病毒" },
            { "svchostc.exe", "疑似杀软进程" },
            { "svchosts.exe", "疑似杀软进程" },
            { "SWAGENT.exe", "SonicWALL" },
            { "swagent.exe", "sonicwall" },
            { "SWDOCTOR.exe", "SonicWALL" },
            { "swdoctor.exe", "sonicwall" },
            { "sweep95.exe", "疑似杀软进程" },
            { "sweepnet.sweepsrv.sys.swnetsup.exe", "疑似杀软进程" },
            { "SWNETSUP.exe", "Sophos" },
            { "swnetsup.exe", "sophos" },
            { "SYMLCSVC.exe", "Symantec" },
            { "symlcsvc.exe", "symantec" },
            { "symproxysvc.exe", "Symantec" },
            { "SYMPROXYSVC.exe", "Symantec" },
            { "SYMSPORT.exe", "Sysmantec" },
            { "symsport.exe", "sysmantec" },
            { "symtray.exe", "Symantec" },
            { "SYMWSC.exe", "Sysmantec" },
            { "symwsc.exe", "sysmantec" },
            { "SYNMGR.exe", "Sysmantec" },
            { "synmgr.exe", "sysmantec" },
            { "SynTPEnh.exe", "笔记本触摸板" },
            { "SynTPEnhService.exe", "笔记本触摸板" },
            { "sysedit.exe", "疑似杀软进程" },
            { "sysupd.exe", "疑似杀软进程" },
            { "Tabby.exe", "Tabby 远程管理工具" },
            { "taskmg.exe", "疑似杀软进程" },
            { "taskmo.exe", "疑似杀软进程" },
            { "taumon.exe", "疑似杀软进程" },
            { "TAUMON.exe", "疑似杀软进程" },
            { "tbmon.exe", "mcafee" },
            { "Tbmon.exe", "Mcafee" },
            { "tbscan.exe", "ThunderBYTE" },
            { "tc.exe", "TimeCalende" },
            { "tca.exe", "疑似杀软进程" },
            { "tcm.exe", "疑似杀软进程" },
            { "tds-3.exe", "疑似杀软进程" },
            { "tds2-98.exe", "疑似杀软进程" },
            { "tds2-nt.exe", "疑似杀软进程" },
            { "TeamViewer.exe", "TeamViewer" },
            { "TeamViewer_Service.exe", "TeamViewer" },
            { "teekids.exe", "疑似杀软进程" },
            { "Telegram.exe", "Telegram" },
            { "tfak.exe", "疑似杀软进程" },
            { "tfak5.exe", "疑似杀软进程" },
            { "tgbob.exe", "疑似杀软进程" },
            { "TitanAgent.exe", "天眼云镜" },
            { "titanin.exe", "TitanHide" },
            { "titaninxp.exe", "疑似杀软进程" },
            { "TitanMonitor.exe", "天眼云镜" },
            { "tmbmsrv.exe", "趋势杀毒" },
            { "TMBMSRV.exe", "趋势杀毒" },
            { "TMLISTEN.exe", "疑似杀软进程" },
            { "tmlisten.exe", "趋势科技" },
            { "tmntsrv.exe", "趋势科技" },
            { "TMNTSRV.exe", "疑似杀软进程" },
            { "tmproxy.exe", "趋势科技" },
            { "TMPROXY.exe", "疑似杀软进程" },
            { "TNBUTIL.exe", "Anti-Virus" },
            { "tnbutil.exe", "anti-virus" },
            { "TNSLSNR.exe", "Oracle 数据库服务" },
            { "Tomcat6.exe", "Tomcat6" },
            { "TopsecMain.exe", "天融信终端防御" },
            { "TopsecTray.exe", "天融信终端防御" },
            { "tracert.exe", "疑似杀软进程" },
            { "trickler.exe", "疑似杀软进程" },
            { "trjscan.exe", "疑似杀软进程" },
            { "TRJSCAN.exe", "疑似杀软进程" },
            { "trjsetup.exe", "疑似杀软进程" },
            { "trojan.exe", "疑似杀软进程" },
            { "TROJAN.exe", "疑似杀软进程" },
            { "trojanhunter.exe", "木马猎手" },
            { "TrojanHunter.exe", "木马猎手" },
            { "trojantrap3.exe", "疑似杀软进程" },
            { "tsadbot.exe", "疑似杀软进程" },
            { "tv_w32.exe", "TeamViewer" },
            { "tv_x64.exe", "TeamViewer" },
            { "tvmd.exe", "Total Velocity" },
            { "tvtmd.exe", "Total Velocity" },
            { "udaterui.exe", "McAfee" },
            { "undoboot.exe", "疑似杀软进程" },
            { "unthreat.exe", "unthreat杀毒" },
            { "UnThreat.exe", "UnThreat杀毒" },
            { "updat.exe", "疑似杀软进程" },
            { "update.exe", "疑似杀软进程" },
            { "updaterui.exe", "McAfee" },
            { "upgrad.exe", "疑似杀软进程" },
            { "usysdiag.exe", "火绒" },
            { "utpost.exe", "疑似杀软进程" },
            { "v3svc.exe", "安博士v3" },
            { "V3Svc.exe", "安博士V3" },
            { "vba32ecm.exe", "疑似杀软进程" },
            { "VBA32ECM.exe", "疑似杀软进程" },
            { "vba32ifs.exe", "疑似杀软进程" },
            { "VBA32IFS.exe", "疑似杀软进程" },
            { "vba32lder.exe", "vb32杀毒" },
            { "vba32ldr.exe", "疑似杀软进程" },
            { "VBA32LDR.exe", "疑似杀软进程" },
            { "vba32pp3.exe", "疑似杀软进程" },
            { "VBA32PP3.exe", "疑似杀软进程" },
            { "vbcmserv.exe", "疑似杀软进程" },
            { "vbcons.exe", "疑似杀软进程" },
            { "vbsntw.exe", "疑似杀软进程" },
            { "VBSNTW.exe", "疑似杀软进程" },
            { "vbust.exe", "疑似杀软进程" },
            { "vbwin9x.exe", "疑似杀软进程" },
            { "vbwinntw.exe", "疑似杀软进程" },
            { "VCRMON.exe", "VirusChaser" },
            { "vcrmon.exe", "viruschaser" },
            { "vcsetup.exe", "疑似杀软进程" },
            { "vet32.exe", "疑似杀软进程" },
            { "vet95.exe", "疑似杀软进程" },
            { "vettray.exe", "eTrust" },
            { "vfsetup.exe", "疑似杀软进程" },
            { "VGAuthService.exe", "Vmware 服务程序 - 提供SAML令牌和票据身份验证【虚拟机程序】" },
            { "vir-help.exe", "疑似杀软进程" },
            { "virusmdpersonalfirewall.exe", "疑似杀软进程" },
            { "vmacthlp.exe", "vmtool【虚拟机程序】" },
            { "vmnat.exe", "VMware NAT Service" },
            { "vmtoolsd.exe", "vmtool【虚拟机程序】" },
            { "vmware-tray", "VMware" },
            { "vmware.exe", "VMware" },
            { "vncserver.exe", "VNC" },
            { "vnlan300.exe", "疑似杀软进程" },
            { "vnpc3000.exe", "疑似杀软进程" },
            { "vpc32.exe", "Symantec" },
            { "vpc42.exe", "Symantec" },
            { "vpfw30s.exe", "疑似杀软进程" },
            { "vptray.exe", "Norton病毒防火墙-盾牌图标程序" },
            { "vrfwsvc.exe", "疑似杀软进程" },
            { "VRFWSVC.exe", "疑似杀软进程" },
            { "VRMONNT.exe", "HAURI" },
            { "vrmonnt.exe", "hauri" },
            { "VRMONSVC.exe", "HAURI" },
            { "vrmonsvc.exe", "hauri" },
            { "vrrw32.exe", "疑似杀软进程" },
            { "VRRW32.exe", "疑似杀软进程" },
            { "vscan40.exe", "疑似杀软进程" },
            { "vscenu6.02d30.exe", "疑似杀软进程" },
            { "vsched.exe", "疑似杀软进程" },
            { "vsecomr.exe", "疑似杀软进程" },
            { "VSECOMR.exe", "疑似杀软进程" },
            { "VSHWIN32.exe", "McAfee" },
            { "vshwin32.exe", "McAfee" },
            { "vsisetup.exe", "疑似杀软进程" },
            { "vsmain.exe", "McAfee" },
            { "vsmon.exe", "ZoneAlarm" },
            { "vsserv.exe", "比特梵德" },
            { "VSSTAT.exe", "McAfee" },
            { "vsstat.exe", "McAfee" },
            { "vstskmgr.exe", "McAfee" },
            { "vswin9xe.exe", "疑似杀软进程" },
            { "vswinntse.exe", "疑似杀软进程" },
            { "vswinperse.exe", "疑似杀软进程" },
            { "w32dsm89.exe", "疑似杀软进程" },
            { "w9x.exe", "疑似杀软进程" },
            { "watchdog.exe", "疑似杀软进程" },
            { "WATCHDOG.exe", "疑似杀软进程" },
            { "wdswfsafe.exe", "360杀毒-网盾" },
            { "webdav.exe", "疑似杀软进程" },
            { "webscanx.exe", "网络病毒克星" },
            { "WEBSCANX.exe", "网络病毒克星" },
            { "webtrap.exe", "疑似杀软进程" },
            { "WeChat.exe", "微信" },
            { "Wechat_Browser.exe", "微信" },
            { "WeChatApp.exe", "微信" },
            { "WechatBrowser.exe", "微信PC微信浏览器" },
            { "WeChatStore.exe", "微信" },
            { "wechatweb.exe", "微信" },
            { "wfindv32.exe", "疑似杀软进程" },
            { "WGestures.exe", "鼠标手势软件" },
            { "WhatsApp.exe", "WhatsApp - 安全可靠的免费私密信息和通话" },
            { "whoswatchingme.exe", "疑似杀软进程" },
            { "wimmun32.exe", "疑似杀软进程" },
            { "win-bugsfix.exe", "疑似杀软进程" },
            { "win32.exe", "疑似杀软进程" },
            { "win32us.exe", "疑似杀软进程" },
            { "winactive.exe", "疑似杀软进程" },
            { "Winaw32.exe", "pcanywhere" },
            { "window.exe", "疑似杀软进程" },
            { "windows.exe", "疑似杀软进程" },
            { "wininetd.exe", "疑似杀软进程" },
            { "wininitx.exe", "疑似杀软进程" },
            { "winlogin.exe", "疑似杀软进程" },
            { "winmain.exe", "疑似杀软进程" },
            { "winnet.exe", "疑似杀软进程" },
            { "winppr32.exe", "疑似杀软进程" },
            { "winrecon.exe", "疑似杀软进程" },
            { "winservn.exe", "疑似杀软进程" },
            { "winssk32.exe", "疑似杀软进程" },
            { "winssnotify.exe", "疑似杀软进程" },
            { "WINSSNOTIFY.exe", "疑似杀软进程" },
            { "winstart.exe", "疑似杀软进程" },
            { "winstart001.exe", "疑似杀软进程" },
            { "wintsk32.exe", "疑似杀软进程" },
            { "winupdate.exe", "疑似杀软进程" },
            { "WINWORD.EXE", "Microsoft Word" },
            { "wkufind.exe", "疑似杀软进程" },
            { "wnad.exe", "疑似杀软进程" },
            { "wnt.exe", "疑似杀软进程" },
            { "wradmin.exe", "疑似杀软进程" },
            { "wrctrl.exe", "疑似杀软进程" },
            { "WRCTRL.exe", "疑似杀软进程" },
            { "wsbgate.exe", "疑似杀软进程" },
            { "wsctrl.exe", "火绒" },
            { "wsctrlsvc.exe", "联想电脑管家(火绒反病毒引擎)" },
            { "wupdater.exe", "疑似杀软进程" },
            { "wupdt.exe", "疑似杀软进程" },
            { "wyvernworksfirewall.exe", "疑似杀软进程" },
            { "XCOMMSVR.exe", "BitDefender" },
            { "xcommsvr.exe", "bitdefender" },
            { "xpf202en.exe", "疑似杀软进程" },
            { "Xshell.exe", "Xshell" },
            { "XshellCore.exe", "Xshell" },
            { "YDLive.exe", "腾讯云-云镜主机安全" },
            { "YDService.exe", "腾讯云-云镜主机安全" },
            { "yunsuo_agent_daemon.exe", "云锁" },
            { "yunsuo_agent_service.exe", "云锁" },
            { "zapro.exe", "Zone Alarm" },
            { "zapsetup3001.exe", "疑似杀软进程" },
            { "zatutor.exe", "疑似杀软进程" },
            { "ZhuDongFangYu.exe", "360安全卫士-主动防御" },
            { "zlclient.exe", "疑似杀软进程" },
            { "ZLCLIENT.exe", "疑似杀软进程" },
            { "zonalm2601.exe", "疑似杀软进程" },
            { "zonealarm.exe", "Zone Alarm" },
            { "ZONEALARM.exe", "Zone Alarm" },
        };

    }
}
